sonar.projectKey=Mohamed-Amine-Mrad_taskflow-devops
sonar.organization=mohamed-amine-mrad

sonar.sources=frontend/src,backend
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
