name: TaskFlow CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Lint backend
        run: |
          cd backend
          npm run lint

      - name: Test backend
        run: |
          cd backend
          npm test

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend Docker image
        run: docker build -t medaminemrad/taskflow-backend:latest ./backend

      - name: Build frontend Docker image
        run: docker build -t medaminemrad/taskflow-frontend:latest ./frontend

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: medaminemrad/taskflow-backend:latest
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: medaminemrad/taskflow-frontend:latest
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

      - name: Push backend Docker image
        run: docker push medaminemrad/taskflow-backend:latest

      - name: Push frontend Docker image
        run: docker push medaminemrad/taskflow-frontend:latest
